from pathlib import Path
import re

p = Path('client/src/components/FloatingTutorial.tsx')
t = p.read_text()

new_guides = r'''const guides: Guide[] = [
  { id: "inicio", title: "Começar no Note Note", area: "Primeiros passos", keywords: ["inicio", "começar", "comecar", "primeiro acesso", "como usar", "ajuda", "dashboard"], intro: "O fluxo do Note Note começa escolhendo o banco em operação, cadastrando clientes e depois criando as operações que você deseja controlar.", steps: ["Confira o banco em operação.", "Abra o Dashboard e personalize os blocos que deseja acompanhar.", "Cadastre o cliente.", "Crie empréstimo, veículo, produto, imóvel, aluguel ou financiamento.", "Registre recebimentos nas áreas correspondentes.", "Acompanhe Contas a receber, Caixa, Agentes e Relatórios."] },
  { id: "dashboard", title: "Usar e personalizar o Dashboard", area: "Dashboard", keywords: ["dashboard", "painel", "blocos", "grafico", "gráfico", "personalizar dashboard"], intro: "O Dashboard reúne os principais indicadores e pode ser ajustado para mostrar apenas os módulos que você quer acompanhar.", steps: ["Abra Dashboard.", "Confira Caixa Geral, Empréstimos, Aluguéis, Imóveis, Veículos, Produtos e Agentes.", "Mostre ou oculte os blocos desejados.", "Abra um bloco em foco para analisar os gráficos daquele módulo."] },
  { id: "clientes", title: "Cadastrar um cliente", area: "Clientes", keywords: ["cliente", "cadastrar cliente", "criar cliente", "novo cliente"], intro: "Clientes são vinculados às operações financeiras, vendas, financiamentos e aluguéis.", steps: ["Abra Clientes.", "Clique para adicionar um cliente.", "Preencha nome, telefone, endereço e demais dados.", "Revise e salve."] },
  { id: "emprestimos", title: "Criar e acompanhar empréstimos", area: "Empréstimos", keywords: ["emprestimo", "empréstimo", "juros", "parcela emprestimo"], intro: "Empréstimos registra valores liberados, juros, parcelas e vencimentos.", steps: ["Abra Empréstimos.", "Selecione o cliente.", "Informe valor, juros, parcelas e datas.", "Confira o cálculo.", "Salve.", "Registre os recebimentos conforme o cliente pagar."] },
  { id: "produtos", title: "Cadastrar produtos e controlar estoque", area: "Produtos", keywords: ["produto", "estoque", "cor produto", "peso", "litro", "unidade", "celular"], intro: "Produtos permite cadastrar itens comercializados e controlar quantidade em estoque.", steps: ["Abra Produtos e crie um produto.", "Informe identificação, características e cor.", "Informe a quantidade em estoque.", "Escolha Unidade, Peso (kg) ou Litro (L).", "Informe preços e demais condições.", "Salve o produto."] },
  { id: "veiculos", title: "Cadastrar veículos", area: "Veículos", keywords: ["veiculo", "veículo", "carro", "placa", "modelo"], intro: "Veículos registra os bens usados nas vendas e financiamentos.", steps: ["Abra Veículos.", "Adicione o veículo.", "Informe marca, modelo, ano, placa, cor e demais dados.", "Adicione imagens quando desejar.", "Revise e salve."] },
  { id: "financiamentos", title: "Financiar veículos e produtos", area: "Financiamentos", keywords: ["financiamento", "veiculo financiado", "produto financiado", "venda financiada"], intro: "Financiamentos cria o contrato parcelado com cliente, bem, entrada, juros e prazo.", steps: ["Cadastre cliente e bem primeiro.", "Abra Financiamentos.", "Crie a operação.", "Informe entrada, juros, prazo e parcelas.", "Confira o cálculo.", "Salve e acompanhe os pagamentos."] },
  { id: "imoveis", title: "Cadastrar e administrar imóveis", area: "Imóveis", keywords: ["imovel", "imóvel", "casa", "apartamento", "terreno", "loja"], intro: "Imóveis reúne casas, apartamentos, terrenos e lojas para venda, financiamento ou aluguel.", steps: ["Abra Imóveis.", "Clique em Novo imóvel.", "Escolha casa, apartamento, terreno ou loja.", "Informe endereço, características e valor.", "Salve.", "Depois escolha Financiar, Vender à vista ou use Aluguéis."] },
  { id: "financiamento-imovel", title: "Criar financiamento de imóvel", area: "Imóveis", keywords: ["financiamento de imovel", "financiamento imóvel", "juros imovel", "parcela imovel", "cancelar financiamento imovel", "excluir financiamento imovel"], intro: "O financiamento imobiliário permite calcular a parcela pela taxa ou descobrir a taxa a partir da parcela desejada.", steps: ["No imóvel disponível, clique em Financiar.", "Escolha o cliente e, se desejar, um agente comissionado.", "Informe entrada e número de parcelas.", "Informe a taxa mensal para calcular a parcela ou deixe a taxa vazia e informe a parcela desejada para calcular os juros.", "Confira valor financiado, taxa, total e parcela.", "Salve.", "Use Cancelar para encerrar a operação ou Excluir quando sua permissão permitir."], tip: "Cancelar preserva o histórico. Exclusões definitivas obedecem às proteções financeiras do sistema." },
  { id: "alugueis", title: "Criar e receber aluguéis", area: "Aluguéis", keywords: ["aluguel", "alugueis", "alugueis", "renda", "mensalidade aluguel"], intro: "Aluguéis cria contratos mensais para imóveis disponíveis.", steps: ["Abra Aluguéis.", "Escolha imóvel e cliente.", "Informe valor mensal, vencimento e início.", "Associe agente e comissão quando houver.", "Salve o contrato.", "Registre os recebimentos mensais.", "Encerre o aluguel quando terminar."] },
  { id: "venda-imovel", title: "Vender imóvel à vista", area: "Imóveis", keywords: ["vender imovel", "venda imovel", "venda à vista imóvel", "vender casa"], intro: "A venda à vista registra o negócio e envia o recebimento para o Caixa.", steps: ["No imóvel disponível, clique em Vender à vista.", "Selecione o cliente.", "Informe o valor recebido.", "Associe agente e comissão quando houver.", "Confirme e confira a entrada no Caixa."] },
  { id: "pagamentos", title: "Registrar pagamentos", area: "Pagamentos", keywords: ["pagamento", "registrar pagamento", "receber parcela", "pagar parcela"], intro: "Pagamentos registra dinheiro efetivamente recebido nas operações disponíveis nesta área.", steps: ["Abra Pagamentos.", "Localize a operação ou parcela.", "Confira cliente, vencimento e valor.", "Registre o pagamento.", "Confira a atualização no Caixa."] },
  { id: "contas-receber", title: "Consultar contas a receber", area: "Contas a receber", keywords: ["contas a receber", "vencimento", "atrasado", "a receber"], intro: "Use esta área para acompanhar valores futuros, próximos e atrasados.", steps: ["Abra Contas a receber.", "Use filtros e períodos.", "Localize cliente e parcela.", "Quando receber, registre o pagamento na área correspondente."] },
  { id: "caixa", title: "Usar o Caixa", area: "Caixa", keywords: ["caixa", "fluxo de caixa", "entrada", "saída", "saida"], intro: "O Caixa reúne movimentações automáticas e manuais do banco selecionado.", steps: ["Abra Caixa.", "Confira entradas e saídas.", "Use filtros.", "Faça lançamentos manuais quando permitido.", "Confira pagamentos, vendas, aluguéis e financiamentos lançados automaticamente."] },
  { id: "agentes", title: "Controlar agentes e comissões", area: "Agentes", keywords: ["agente", "comissão", "comissao", "vendedor", "captador"], intro: "Agentes controla pessoas comissionadas ligadas às operações.", steps: ["Cadastre o agente.", "Defina a comissão padrão.", "Associe-o às operações compatíveis.", "Confira comissão e valor líquido.", "Use o histórico para acompanhar desempenho.", "Desative sem apagar o histórico quando necessário."] },
  { id: "relatorios", title: "Usar relatórios e exportações", area: "Relatórios", keywords: ["relatório", "relatorio", "excel", "exportar"], intro: "Relatórios reúne análises e exportações dos dados da operação.", steps: ["Abra Relatórios.", "Escolha a análise.", "Defina período e filtros.", "Confira os resultados.", "Exporte quando disponível."] },
  { id: "banco", title: "Usar bancos de dados", area: "Bancos", keywords: ["banco", "banco em operação", "meu banco", "trocar banco"], intro: "Cada banco separa clientes e operações. O banco em operação define os dados exibidos.", steps: ["Confira Banco em operação.", "Selecione apenas um banco liberado para sua conta.", "Use Meu Banco para administrar as opções permitidas.", "No Plus, distribua acesso aos bancos para os usuários da equipe."] },
  { id: "equipe", title: "Gerenciar equipe e permissões", area: "Equipe", keywords: ["equipe", "usuario adicional", "usuário adicional", "permissão", "permissao"], intro: "A equipe permite controlar quais bancos e ações cada usuário pode acessar.", steps: ["Abra Equipe.", "Crie ou edite o usuário.", "Escolha os bancos.", "Marque apenas as permissões necessárias.", "Salve e teste o acesso."] },
  { id: "perfil", title: "Usar Meu Perfil e assinatura", area: "Perfil", keywords: ["perfil", "assinatura", "plano", "alterar senha", "validade"], intro: "Meu Perfil reúne seus dados e informações da assinatura.", steps: ["Abra Meu Perfil.", "Revise nome, usuário, e-mail e WhatsApp.", "Confira plano, status, teste e validade.", "Altere dados ou senha quando necessário.", "Use as opções de assinatura disponíveis com confirmação de senha."] },
  { id: "primeiro-acesso", title: "Concluir pagamento e primeiro acesso", area: "Cadastro e assinatura", keywords: ["primeiro acesso", "pagamento pendente", "continuar pagamento", "pix", "cartão", "cartao", "asaas"], intro: "Novos assinantes só entram na operação depois de concluir as etapas exigidas no pagamento.", steps: ["Escolha o plano e a forma de pagamento.", "Preencha o cadastro e aceite os termos.", "Conclua cartão ou Pix no fluxo do Asaas.", "Se sair antes de terminar, volte ao login com o mesmo usuário.", "O Note Note mostra a etapa em que você parou.", "Depois da confirmação exigida, o primeiro acesso é liberado."] },
  { id: "admin-controle", title: "Usar o Painel de Controle", area: "Super Admin", keywords: ["painel de controle", "super admin", "controle"], intro: "O Painel de Controle reúne a visão administrativa geral do Note Note.", steps: ["Abra Administração > Painel de Controle.", "Confira os indicadores gerais.", "Use Assinaturas, Usuários, Bancos, Marketing e Auditoria para tarefas específicas."], adminOnly: true },
  { id: "admin-assinaturas", title: "Administrar assinaturas", area: "Super Admin", keywords: ["assinaturas", "assinante", "cancelar assinatura", "excel assinaturas"], intro: "Assinaturas reúne clientes comerciais, plano, cobrança, status e ações administrativas.", steps: ["Abra Assinaturas.", "Localize o cliente.", "Confira plano e pagamento.", "Use as ações disponíveis com confirmação quando exigida.", "Exporte a lista detalhada quando necessário."], adminOnly: true },
  { id: "admin-bancos-clientes", title: "Acessar bancos de clientes com segurança", area: "Super Admin", keywords: ["banco cliente", "bancos de clientes", "senha super admin", "area protegida"], intro: "Bancos de clientes comerciais não aparecem no seletor Banco em operação do Super Admin.", steps: ["Abra Administração > Bancos de Dados.", "Entre em Bancos de Clientes — Área Protegida.", "Digite a senha do Super Admin.", "Escolha o banco do cliente.", "Confirme a senha novamente quando solicitado.", "Use somente esse caminho protegido para consultar dados de clientes."], adminOnly: true },
  { id: "admin-marketing", title: "Enviar campanhas de marketing", area: "Super Admin", keywords: ["marketing", "campanha", "email marketing", "e-mail marketing"], intro: "Marketing permite enviar campanhas aos clientes elegíveis que autorizaram comunicações.", steps: ["Abra Marketing.", "Escolha o público.", "Crie assunto e mensagem.", "Adicione imagem quando desejar.", "Revise e envie."], adminOnly: true },
  { id: "admin-auditoria", title: "Consultar auditoria", area: "Super Admin", keywords: ["auditoria", "log", "consentimento", "historico admin"], intro: "Auditoria registra ações administrativas e eventos importantes de segurança.", steps: ["Abra Auditoria.", "Use filtros.", "Confira usuário, data, entidade e detalhes.", "Use o histórico para rastrear alterações e acessos protegidos."], adminOnly: true },
];'''

t, n = re.subn(r'const guides: Guide\[\] = \[.*?\n\];\n\nconst quickTopics', new_guides + '\n\nconst quickTopics', t, count=1, flags=re.S)
if n != 1:
    raise SystemExit('Could not replace guides array')

t = re.sub(r'const quickTopics = \[.*?\];', 'const quickTopics = ["Como começar?", "Dashboard", "Cadastrar cliente", "Empréstimos", "Produtos e estoque", "Veículos", "Financiamento", "Imóveis", "Financiar imóvel", "Aluguéis", "Pagamentos", "Agentes", "Caixa", "Contas a receber", "Meu Perfil"];', t, count=1, flags=re.S)

route_old = r'function routeGuide\(path: string, available: Guide\[\]\) \{.*?\}\nfunction clampPosition'
route_new = '''function routeGuide(path: string, available: Guide[]) { const routeMap: Array<[string, string]> = [["/dashboard", "dashboard"], ["/clientes", "clientes"], ["/emprestimos", "emprestimos"], ["/pagamentos", "pagamentos"], ["/agentes", "agentes"], ["/veiculos", "veiculos"], ["/produtos", "produtos"], ["/imoveis", "imoveis"], ["/alugueis", "alugueis"], ["/financiamentos", "financiamentos"], ["/caixa", "caixa"], ["/contas-a-receber", "contas-receber"], ["/relatorios", "relatorios"], ["/perfil", "perfil"], ["/equipe", "equipe"], ["/meu-banco", "banco"], ["/admin/controle", "admin-controle"], ["/admin/usuarios", "equipe"], ["/admin/bancos", "admin-bancos-clientes"], ["/admin/assinaturas", "admin-assinaturas"], ["/admin/marketing", "admin-marketing"], ["/admin/auditoria", "admin-auditoria"]]; const match = routeMap.find(([prefix]) => path.startsWith(prefix)); return available.find(item => item.id === (match?.[1] ?? "inicio")) ?? available[0]; }
function clampPosition'''
t, n = re.subn(route_old, route_new, t, count=1, flags=re.S)
if n != 1:
    raise SystemExit('Could not replace routeGuide')

old_fallback = 'Tente usar o nome da função, como cliente, empréstimo, agente, produto, veículo, financiamento, pagamento, caixa ou relatório.'
new_fallback = 'Tente usar o nome da função, como dashboard, cliente, empréstimo, produto, estoque, veículo, imóvel, aluguel, financiamento, pagamento, agente, caixa, relatório, perfil ou banco.'
t = t.replace(old_fallback, new_fallback)

p.write_text(t)
