import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/_core/hooks/useAuth";
import { Building2, Home, MapPin, Plus, Trash2, WalletCards, BadgeDollarSign, ReceiptText } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const API="/api/site-access?scope=properties";
const money=(v:any)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const typeLabel:Record<string,string>={casa:"Casa",apartamento:"Apartamento",terreno:"Terreno",loja:"Loja"};
const emptyProperty=()=>({title:"",type:"casa",address:"",neighborhood:"",city:"",state:"",zipCode:"",areaM2:"",rooms:"0",bedrooms:"0",livingRooms:"0",kitchens:"0",bathrooms:"0",garages:"0",hasGarage:false,salePrice:"",notes:""});
const emptyFinancing=()=>({propertyId:"",clientId:"",salePrice:"",downPayment:"0",interestRate:"",installments:"",startDate:new Date().toISOString().slice(0,10),notes:""});
const emptySale=()=>({propertyId:"",clientId:"",amount:"",notes:""});

export default function Imoveis(){
  const {user}=useAuth();
  const [data,setData]=useState<any>({properties:[],clients:[],financings:[],financingPayments:[],sales:[]});
  const [loading,setLoading]=useState(true);
  const [open,setOpen]=useState(false),[openFinance,setOpenFinance]=useState(false),[openSale,setOpenSale]=useState(false);
  const [form,setForm]=useState(emptyProperty),[finance,setFinance]=useState(emptyFinancing),[sale,setSale]=useState(emptySale);
  const load=async()=>{setLoading(true);try{const r=await fetch(API,{credentials:"include"});const j=await r.json();if(!r.ok)throw new Error(j.message);setData(j);}catch(e){toast.error(e instanceof Error?e.message:"Erro ao carregar imóveis.");}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const post=async(body:any)=>{const r=await fetch(API,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.message||"Operação não concluída.");return j;};
  const summary=useMemo(()=>({total:data.properties.length,available:data.properties.filter((p:any)=>p.status==="disponivel").length,rented:data.properties.filter((p:any)=>p.status==="alugado").length,financed:data.properties.filter((p:any)=>p.status==="financiado").length,sold:data.properties.filter((p:any)=>p.status==="vendido").length}),[data.properties]);
  const save=async(e:React.FormEvent)=>{e.preventDefault();try{await post({action:"create_property",...form});toast.success("Imóvel cadastrado.");setOpen(false);setForm(emptyProperty());await load();}catch(e){toast.error(e instanceof Error?e.message:"Erro ao cadastrar imóvel.");}};
  const remove=async(id:number)=>{if(!confirm("Excluir este imóvel?"))return;try{await post({action:"delete_property",id});toast.success("Imóvel excluído.");await load();}catch(e){toast.error(e instanceof Error?e.message:"Erro ao excluir.");}};
  const startFinance=(p:any)=>{setFinance({...emptyFinancing(),propertyId:String(p.id),salePrice:String(p.salePrice||"")});setOpenFinance(true);};
  const startSale=(p:any)=>{setSale({...emptySale(),propertyId:String(p.id),amount:String(p.salePrice||"")});setOpenSale(true);};
  const saveFinance=async(e:React.FormEvent)=>{e.preventDefault();try{await post({action:"create_financing",...finance});toast.success("Financiamento imobiliário criado. A entrada foi lançada no caixa.");setOpenFinance(false);setFinance(emptyFinancing());await load();}catch(e){toast.error(e instanceof Error?e.message:"Erro ao financiar imóvel.");}};
  const saveSale=async(e:React.FormEvent)=>{e.preventDefault();try{await post({action:"sell_cash",...sale});toast.success("Venda registrada e valor lançado no caixa.");setOpenSale(false);setSale(emptySale());await load();}catch(e){toast.error(e instanceof Error?e.message:"Erro ao vender imóvel.");}};
  const payFinancing=async(f:any)=>{const paid=(data.financingPayments||[]).filter((p:any)=>Number(p.financingId)===Number(f.id)).map((p:any)=>Number(p.installmentNumber));let next=1;while(paid.includes(next)&&next<=Number(f.installments))next++;if(next>Number(f.installments))return toast.info("Todas as parcelas já foram pagas.");if(!confirm(`Registrar pagamento da parcela ${next}/${f.installments} no valor de ${money(f.installmentAmount)}?`))return;try{await post({action:"pay_financing",financingId:f.id,installmentNumber:next,amount:f.installmentAmount});toast.success("Parcela recebida e lançada no caixa.");await load();}catch(e){toast.error(e instanceof Error?e.message:"Erro ao registrar parcela.");}};
  const calc=useMemo(()=>{const saleValue=Number(finance.salePrice),down=Number(finance.downPayment),rate=Number(finance.interestRate),n=Number(finance.installments);const principal=Math.max(0,saleValue-down);const total=n>0?principal+(principal*Math.max(0,rate)/100)*n:0;return {principal,total,installment:n>0?total/n:0};},[finance]);

  return <DashboardLayout><div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Building2 className="h-7 w-7 text-primary"/><h1 className="text-3xl font-bold">Imóveis</h1></div><p className="mt-1 text-muted-foreground">Casas, apartamentos, terrenos e lojas para aluguel, venda à vista ou financiamento.</p></div>{user?.canInsert&&<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus className="mr-2 h-4 w-4"/>Novo imóvel</Button></DialogTrigger><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>Cadastrar imóvel</DialogTitle></DialogHeader><form onSubmit={save} className="grid gap-4 sm:grid-cols-2">
      <div><Label>Identificação *</Label><Input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ex.: Casa Centro" required/></div>
      <div><Label>Categoria do imóvel *</Label><Select value={form.type} onValueChange={v=>setForm({...form,type:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="casa">Casa</SelectItem><SelectItem value="apartamento">Apartamento</SelectItem><SelectItem value="terreno">Terreno</SelectItem><SelectItem value="loja">Loja</SelectItem></SelectContent></Select></div>
      <div className="sm:col-span-2"><Label>Endereço *</Label><Input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Rua, número e complemento" required/></div>
      <div><Label>Bairro</Label><Input value={form.neighborhood} onChange={e=>setForm({...form,neighborhood:e.target.value})}/></div><div><Label>Cidade</Label><Input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></div>
      <div><Label>Estado</Label><Input maxLength={2} value={form.state} onChange={e=>setForm({...form,state:e.target.value.toUpperCase()})}/></div><div><Label>CEP</Label><Input value={form.zipCode} onChange={e=>setForm({...form,zipCode:e.target.value})}/></div>
      <div><Label>Tamanho (m²)</Label><Input type="number" min="0" step="0.01" value={form.areaM2} onChange={e=>setForm({...form,areaM2:e.target.value})}/></div><div><Label>Valor de venda</Label><Input type="number" min="0" step="0.01" value={form.salePrice} onChange={e=>setForm({...form,salePrice:e.target.value})}/></div>
      {[["rooms","Cômodos"],["bedrooms","Quartos"],["livingRooms","Salas"],["kitchens","Cozinhas"],["bathrooms","Banheiros"],["garages","Vagas de garagem"]].map(([key,label])=><div key={key}><Label>{label}</Label><Input type="number" min="0" step="1" value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></div>)}
      <label className="flex items-center gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={form.hasGarage} onChange={e=>setForm({...form,hasGarage:e.target.checked})}/> Possui garagem</label>
      <div className="sm:col-span-2"><Label>Outras informações</Label><Textarea rows={4} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Condomínio, IPTU, área externa, estado de conservação, documentação..."/></div>
      <div className="sm:col-span-2 flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit">Salvar imóvel</Button></div>
    </form></DialogContent></Dialog>}</div>

    <div className="grid gap-3 sm:grid-cols-5">{[["Cadastrados",summary.total],["Disponíveis",summary.available],["Alugados",summary.rented],["Financiados",summary.financed],["Vendidos",summary.sold]].map(([l,v])=><Card key={String(l)}><CardContent className="p-4"><p className="text-sm text-muted-foreground">{l}</p><p className="text-2xl font-bold">{v}</p></CardContent></Card>)}</div>

    {loading?<div className="py-16 text-center text-muted-foreground">Carregando imóveis...</div>:data.properties.length===0?<Card><CardContent className="py-16 text-center"><Home className="mx-auto mb-3 h-10 w-10 text-muted-foreground"/><p className="font-semibold">Nenhum imóvel cadastrado</p></CardContent></Card>:<div className="grid gap-4 lg:grid-cols-2">{data.properties.map((p:any)=><Card key={p.id}><CardContent className="p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h3 className="text-lg font-bold">{p.title}</h3><span className="rounded-full bg-muted px-2 py-1 text-[10px] font-bold uppercase">{p.status}</span></div><p className="mt-1 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="h-4 w-4"/>{p.address}</p></div><span className="rounded-lg bg-primary/10 px-2 py-1 text-xs font-semibold text-primary">{typeLabel[p.type]||p.type}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm sm:grid-cols-4"><div><span className="text-muted-foreground">Área</span><b className="block">{p.areaM2?`${p.areaM2} m²`:"—"}</b></div><div><span className="text-muted-foreground">Quartos</span><b className="block">{p.bedrooms}</b></div><div><span className="text-muted-foreground">Banheiros</span><b className="block">{p.bathrooms}</b></div><div><span className="text-muted-foreground">Garagem</span><b className="block">{p.hasGarage?`${p.garages||1} vaga(s)`:"Não"}</b></div></div>{p.salePrice&&<div className="mt-4 rounded-xl bg-muted/40 p-3"><span className="text-xs text-muted-foreground">Valor de venda</span><div className="text-xl font-bold">{money(p.salePrice)}</div></div>}<div className="mt-4 flex flex-wrap gap-2">{user?.canInsert&&p.status==="disponivel"&&<><Button size="sm" onClick={()=>startFinance(p)}><WalletCards className="mr-2 h-4 w-4"/>Financiar</Button><Button size="sm" variant="secondary" onClick={()=>startSale(p)}><BadgeDollarSign className="mr-2 h-4 w-4"/>Vender à vista</Button></>}{user?.canDelete&&<Button size="sm" variant="outline" className="text-destructive" onClick={()=>remove(p.id)}><Trash2 className="mr-2 h-4 w-4"/>Excluir</Button>}</div></CardContent></Card>)}</div>}

    {data.financings?.length>0&&<Card><CardHeader><CardTitle className="flex items-center gap-2"><ReceiptText className="h-5 w-5 text-primary"/>Financiamentos de imóveis</CardTitle></CardHeader><CardContent className="space-y-3">{data.financings.map((f:any)=>{const paid=(data.financingPayments||[]).filter((p:any)=>Number(p.financingId)===Number(f.id)).length;const totalReceived=Number(f.downPayment||0)+Number(f.totalPaid||0);return <div key={f.id} className="rounded-xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{f.propertyTitle} <span className="text-xs font-normal text-muted-foreground">· {typeLabel[f.propertyType]||f.propertyType}</span></p><p className="text-sm text-muted-foreground">Cliente: {f.clientName} · {paid}/{f.installments} parcelas pagas</p></div><div className="text-right"><p className="font-semibold">{money(f.installmentAmount)} / parcela</p><p className="text-xs text-muted-foreground">Recebido: {money(totalReceived)}</p></div></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{width:`${Math.min(100,(paid/Math.max(1,Number(f.installments)))*100)}%`}}/></div>{user?.canEdit&&f.status==="ativo"&&<div className="mt-3 flex justify-end"><Button size="sm" onClick={()=>payFinancing(f)}>Registrar próxima parcela</Button></div>}</div>})}</CardContent></Card>}

    <Dialog open={openFinance} onOpenChange={setOpenFinance}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Financiamento de imóvel</DialogTitle></DialogHeader><form onSubmit={saveFinance} className="grid gap-4 sm:grid-cols-2"><div><Label>Cliente *</Label><Select value={finance.clientId} onValueChange={v=>setFinance({...finance,clientId:v})}><SelectTrigger><SelectValue placeholder="Selecionar cliente"/></SelectTrigger><SelectContent>{data.clients.map((c:any)=><SelectItem key={c.id} value={String(c.id)}>{c.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Valor da venda *</Label><Input type="number" min="0.01" step="0.01" value={finance.salePrice} onChange={e=>setFinance({...finance,salePrice:e.target.value})} required/></div><div><Label>Entrada *</Label><Input type="number" min="0" step="0.01" value={finance.downPayment} onChange={e=>setFinance({...finance,downPayment:e.target.value})} required/></div><div><Label>Juros ao mês (%) *</Label><Input type="number" min="0" step="0.01" value={finance.interestRate} onChange={e=>setFinance({...finance,interestRate:e.target.value})} required/></div><div><Label>Parcelas *</Label><Input type="number" min="1" step="1" value={finance.installments} onChange={e=>setFinance({...finance,installments:e.target.value})} required/></div><div><Label>Data inicial *</Label><Input type="date" value={finance.startDate} onChange={e=>setFinance({...finance,startDate:e.target.value})} required/></div><div className="sm:col-span-2 grid gap-2 rounded-xl border bg-muted/30 p-4 sm:grid-cols-3"><div><span className="text-xs text-muted-foreground">Financiado</span><b className="block">{money(calc.principal)}</b></div><div><span className="text-xs text-muted-foreground">Total com juros</span><b className="block">{money(calc.total)}</b></div><div><span className="text-xs text-muted-foreground">Parcela</span><b className="block">{money(calc.installment)}</b></div></div><div className="sm:col-span-2"><Label>Observações</Label><Textarea value={finance.notes} onChange={e=>setFinance({...finance,notes:e.target.value})}/></div><div className="sm:col-span-2 flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpenFinance(false)}>Cancelar</Button><Button type="submit">Criar financiamento</Button></div></form></DialogContent></Dialog>

    <Dialog open={openSale} onOpenChange={setOpenSale}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Venda de imóvel à vista</DialogTitle></DialogHeader><form onSubmit={saveSale} className="space-y-4"><div><Label>Cliente *</Label><Select value={sale.clientId} onValueChange={v=>setSale({...sale,clientId:v})}><SelectTrigger><SelectValue placeholder="Selecionar cliente"/></SelectTrigger><SelectContent>{data.clients.map((c:any)=><SelectItem key={c.id} value={String(c.id)}>{c.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Valor da venda *</Label><Input type="number" min="0.01" step="0.01" value={sale.amount} onChange={e=>setSale({...sale,amount:e.target.value})} required/></div><div><Label>Observações</Label><Textarea value={sale.notes} onChange={e=>setSale({...sale,notes:e.target.value})}/></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpenSale(false)}>Cancelar</Button><Button type="submit">Confirmar venda</Button></div></form></DialogContent></Dialog>
  </div></DashboardLayout>;
}
