import { getSql, readCookie, readJsonBody, sendJson, SESSION_COOKIE_NAME } from "../api/auth/_shared.js";

type User={id:number;role:string;name?:string|null;username?:string|null};
let schemaPromise:Promise<void>|null=null;
function ensureSchema(){if(schemaPromise)return schemaPromise;const sql=getSql();schemaPromise=(async()=>{await sql`CREATE TABLE IF NOT EXISTS monthly_closings (id bigserial PRIMARY KEY,"databaseId" integer NOT NULL REFERENCES databases(id) ON DELETE CASCADE,"month" varchar(7) NOT NULL,"snapshot" jsonb NOT NULL,"closedBy" integer REFERENCES users(id) ON DELETE SET NULL,"closedAt" timestamptz NOT NULL DEFAULT NOW(),UNIQUE("databaseId","month"))`;await sql`CREATE INDEX IF NOT EXISTS monthly_closings_database_month_idx ON monthly_closings ("databaseId","month" DESC)`;})().catch(e=>{schemaPromise=null;throw e});return schemaPromise;}
async function userFromSession(req:any):Promise<User|null>{const token=readCookie(req,SESSION_COOKIE_NAME);if(!token)return null;const sql=getSql();const rows=await sql`SELECT u.id,u.role,u.name,u.username FROM local_sessions s JOIN users u ON u.id=s."userId" WHERE s.token=${token} AND s."expiresAt">NOW() LIMIT 1`;return (rows[0] as any)||null;}
async function canAccessDatabase(user:User,databaseId:number){const sql=getSql();if(user.role==='super_admin'){const rows=await sql`SELECT id FROM databases WHERE id=${databaseId} LIMIT 1`;return Boolean(rows[0]);}const rows=await sql`SELECT 1 FROM user_database_access WHERE "userId"=${user.id} AND "databaseId"=${databaseId} LIMIT 1`;return Boolean(rows[0]);}
function validMonth(value:unknown){const m=String(value??'').trim();return /^\d{4}-(0[1-9]|1[0-2])$/.test(m)?m:null;}
function safeSnapshot(value:any){if(!value||typeof value!=='object'||Array.isArray(value))return null;const raw=JSON.stringify(value);if(raw.length>50000)return null;return value;}
export async function handleMonthlyClosings(req:any,res:any){try{await ensureSchema();const user=await userFromSession(req);if(!user)return sendJson(res,401,{success:false,message:'Sessão expirada.'});const sql=getSql();const databaseId=Math.trunc(Number(Array.isArray(req?.query?.databaseId)?req.query.databaseId[0]:req?.query?.databaseId||0));if(!databaseId)return sendJson(res,400,{success:false,message:'Selecione um banco de dados.'});if(!(await canAccessDatabase(user,databaseId)))return sendJson(res,403,{success:false,message:'Sem acesso a este banco de dados.'});
if(req.method==='GET'){const rows=await sql`SELECT mc.id,mc."databaseId",mc.month,mc.snapshot,mc."closedAt",mc."closedBy",COALESCE(NULLIF(u.name,''),NULLIF(u.username,''),'Usuário') AS "closedByName" FROM monthly_closings mc LEFT JOIN users u ON u.id=mc."closedBy" WHERE mc."databaseId"=${databaseId} ORDER BY mc.month DESC`;return sendJson(res,200,{success:true,closings:rows});}
if(req.method==='POST'){const body=await readJsonBody(req);const month=validMonth(body?.month);const snapshot=safeSnapshot(body?.snapshot);if(!month)return sendJson(res,400,{success:false,message:'Mês de fechamento inválido.'});const current=new Date().toISOString().slice(0,7);if(month>current)return sendJson(res,400,{success:false,message:'Não é possível fechar um mês futuro.'});if(!snapshot)return sendJson(res,400,{success:false,message:'Dados do fechamento inválidos.'});try{const rows=await sql`INSERT INTO monthly_closings ("databaseId",month,snapshot,"closedBy","closedAt") VALUES (${databaseId},${month},${JSON.stringify(snapshot)}::jsonb,${user.id},NOW()) RETURNING id,"databaseId",month,snapshot,"closedAt"`;return sendJson(res,201,{success:true,closing:rows[0],message:'Fechamento mensal registrado com sucesso.'});}catch(error:any){if(String(error?.code||'')==='23505')return sendJson(res,409,{success:false,message:'Este mês já foi fechado. Consulte-o em Fechamentos.'});throw error;}}
res.setHeader('Allow','GET, POST');return sendJson(res,405,{success:false,message:'Método não permitido.'});}catch(error){console.error('[monthly-closings]',error);return sendJson(res,500,{success:false,message:error instanceof Error?error.message:'Erro ao processar fechamento mensal.'});}}
