import { getSql, readCookie, readJsonBody, sendJson, SESSION_COOKIE_NAME } from "../api/auth/_shared.js";

type SessionUser = { id:number; role:string; loginMethod?:string|null; accountOwnerId?:number|null; name?:string|null; username?:string|null };
let schemaPromise:Promise<void>|null=null;
function ensureSchema(){if(schemaPromise)return schemaPromise;const sql=getSql();schemaPromise=(async()=>{await sql`CREATE TABLE IF NOT EXISTS customer_reviews (id bigserial PRIMARY KEY,"userId" integer NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5),comment text NOT NULL,"published" boolean NOT NULL DEFAULT false,"publishedAt" timestamptz,"createdAt" timestamptz NOT NULL DEFAULT NOW(),"updatedAt" timestamptz NOT NULL DEFAULT NOW())`;await sql`CREATE INDEX IF NOT EXISTS customer_reviews_published_idx ON customer_reviews (published,"publishedAt" DESC,"updatedAt" DESC)`;})().catch(e=>{schemaPromise=null;throw e});return schemaPromise;}
function clean(value:unknown,max=1200){return String(value??"").trim().slice(0,max)}
async function session(req:any):Promise<SessionUser|null>{const token=readCookie(req,SESSION_COOKIE_NAME);if(!token)return null;const sql=getSql();const rows=await sql`SELECT u.id,u.role,u."loginMethod",u."accountOwnerId",u.name,u.username FROM local_sessions s JOIN users u ON u.id=s."userId" WHERE s.token=${token} AND s."expiresAt">NOW() LIMIT 1`;return (rows[0] as any)||null}
async function ownerFor(user:SessionUser){return user.loginMethod==='commercial_signup'?user:null}
export async function handleReviews(req:any,res:any){try{await ensureSchema();const sql=getSql();const action=clean(Array.isArray(req?.query?.action)?req.query.action[0]:req?.query?.action,40).toLowerCase();
if(req.method==='GET'&&action==='published'){const rows=await sql`SELECT r.id,r.rating,r.comment,r."publishedAt",COALESCE(NULLIF(u.name,''),NULLIF(u.username,''),'Cliente Note Note') AS name FROM customer_reviews r JOIN users u ON u.id=r."userId" WHERE r.published=true ORDER BY r."publishedAt" DESC NULLS LAST,r."updatedAt" DESC LIMIT 12`;return sendJson(res,200,{success:true,reviews:rows});}
const user=await session(req);if(!user)return sendJson(res,401,{success:false,message:'Sessão expirada.'});
if(req.method==='GET'&&action==='mine'){const owner=await ownerFor(user);if(!owner)return sendJson(res,403,{success:false,message:'Avaliações estão disponíveis para o titular da assinatura.'});const rows=await sql`SELECT id,rating,comment,published,"publishedAt","createdAt","updatedAt" FROM customer_reviews WHERE "userId"=${Number(owner.id)} LIMIT 1`;return sendJson(res,200,{success:true,review:rows[0]||null});}
if(req.method==='POST'&&action==='mine'){const owner=await ownerFor(user);if(!owner)return sendJson(res,403,{success:false,message:'Avaliações estão disponíveis para o titular da assinatura.'});const body=await readJsonBody(req);const rating=Math.trunc(Number(body?.rating));const comment=clean(body?.comment,1200);if(rating<1||rating>5)return sendJson(res,400,{success:false,message:'Escolha uma avaliação de 1 a 5 estrelas.'});if(comment.length<3)return sendJson(res,400,{success:false,message:'Escreva um comentário, sugestão ou elogio.'});const rows=await sql`INSERT INTO customer_reviews ("userId",rating,comment,published,"publishedAt","updatedAt") VALUES (${Number(owner.id)},${rating},${comment},false,NULL,NOW()) ON CONFLICT ("userId") DO UPDATE SET rating=EXCLUDED.rating,comment=EXCLUDED.comment,published=false,"publishedAt"=NULL,"updatedAt"=NOW() RETURNING id,rating,comment,published,"publishedAt","createdAt","updatedAt"`;return sendJson(res,200,{success:true,review:rows[0],message:'Avaliação enviada para análise. Obrigado!'});}
if(user.role!=='super_admin')return sendJson(res,403,{success:false,message:'Acesso restrito ao Super Admin.'});
if(req.method==='GET'&&(!action||action==='admin')){const rows=await sql`SELECT r.id,r.rating,r.comment,r.published,r."publishedAt",r."createdAt",r."updatedAt",u.id AS "userId",u."supportId",u.name,u.username,u.email FROM customer_reviews r JOIN users u ON u.id=r."userId" ORDER BY r."updatedAt" DESC`;return sendJson(res,200,{success:true,reviews:rows});}
if(req.method==='POST'&&['publish','unpublish','delete'].includes(action)){const body=await readJsonBody(req);const id=Math.trunc(Number(body?.id));if(!id)return sendJson(res,400,{success:false,message:'Avaliação inválida.'});if(action==='delete'){await sql`DELETE FROM customer_reviews WHERE id=${id}`;return sendJson(res,200,{success:true});}const published=action==='publish';await sql`UPDATE customer_reviews SET published=${published},"publishedAt"=${published?new Date():null},"updatedAt"=NOW() WHERE id=${id}`;return sendJson(res,200,{success:true,published});}
return sendJson(res,405,{success:false,message:'Método ou ação inválida.'});}catch(error){console.error('[reviews]',error);return sendJson(res,500,{success:false,message:error instanceof Error?error.message:'Erro nas avaliações.'});}}
