import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Check, EyeOff, RefreshCw, Star, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";

type Review={id:number;rating:number;comment:string;published:boolean;publishedAt?:string|null;createdAt:string;updatedAt:string;userId:number;supportId?:string|null;name?:string|null;username?:string|null;email?:string|null};
const API="/api/site-access?scope=reviews";
function Stars({value}:{value:number}){return <div className="flex gap-0.5" aria-label={`${value} de 5 estrelas`}>{[1,2,3,4,5].map(n=><Star key={n} className={`h-4 w-4 ${n<=value?"fill-amber-400 text-amber-400":"text-muted-foreground/30"}`}/>)}</div>}
export default function AdminAvaliacoes(){const [reviews,setReviews]=useState<Review[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<number|null>(null);
const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(`${API}&action=admin`,{credentials:"include",cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j?.message||"Erro ao carregar avaliações.");setReviews(Array.isArray(j.reviews)?j.reviews:[])}catch(e){toast.error(e instanceof Error?e.message:"Erro ao carregar avaliações.")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
const act=async(id:number,action:"publish"|"unpublish"|"delete")=>{if(action==="delete"&&!confirm("Excluir esta avaliação permanentemente?"))return;setBusy(id);try{const r=await fetch(`${API}&action=${action}`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({id})});const j=await r.json();if(!r.ok)throw new Error(j?.message||"Não foi possível concluir a ação.");toast.success(action==="publish"?"Avaliação publicada no site.":action==="unpublish"?"Avaliação retirada do site.":"Avaliação excluída.");await load()}catch(e){toast.error(e instanceof Error?e.message:"Erro na avaliação.")}finally{setBusy(null)}};
return <DashboardLayout><div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Super Admin</p><h1 className="text-2xl font-bold">Avaliações dos clientes</h1><p className="text-sm text-muted-foreground">Analise sugestões e elogios e escolha quais depoimentos aparecem no site.</p></div><Button variant="outline" onClick={()=>load()} disabled={loading}><RefreshCw className="mr-2 h-4 w-4"/>Atualizar</Button></div>{loading?<Card><CardContent className="py-12 text-center text-muted-foreground">Carregando avaliações...</CardContent></Card>:reviews.length===0?<Card><CardContent className="py-12 text-center text-muted-foreground">Nenhuma avaliação recebida ainda.</CardContent></Card>:<div className="grid gap-4 lg:grid-cols-2">{reviews.map(review=><Card key={review.id} className={review.published?"border-primary/30":""}><CardHeader className="pb-3"><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-base">{review.name||review.username||"Cliente Note Note"}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{review.email||"—"} {review.supportId?`• ID ${review.supportId}`:""}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${review.published?"bg-emerald-500/10 text-emerald-700":"bg-muted text-muted-foreground"}`}>{review.published?"Publicado":"Aguardando publicação"}</span></div><div className="mt-2"><Stars value={Number(review.rating)}/></div></CardHeader><CardContent><p className="min-h-16 whitespace-pre-wrap text-sm leading-6">{review.comment}</p><p className="mt-3 text-xs text-muted-foreground">Atualizado em {new Date(review.updatedAt).toLocaleString("pt-BR")}</p><div className="mt-4 flex flex-wrap gap-2">{review.published?<Button size="sm" variant="outline" disabled={busy===review.id} onClick={()=>act(review.id,"unpublish")}><EyeOff className="mr-2 h-4 w-4"/>Retirar do site</Button>:<Button size="sm" disabled={busy===review.id} onClick={()=>act(review.id,"publish")}><Check className="mr-2 h-4 w-4"/>Publicar no site</Button>}<Button size="sm" variant="destructive" disabled={busy===review.id} onClick={()=>act(review.id,"delete")}><Trash2 className="mr-2 h-4 w-4"/>Excluir</Button></div></CardContent></Card>)}</div>}</div></DashboardLayout>}
