import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Clock3, Eye, Globe2, LoaderCircle, MapPin, MonitorSmartphone, RefreshCw, Search, UserCheck, Users } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";

type Visitor={visitorId:string;label:string;name?:string;email?:string;anonymous:boolean;converted:boolean;firstSeen:string;lastSeen:string;pageViews:number;sessions:number;pages:string[];city?:string;region?:string;country?:string;language?:string;screen?:string;maskedIp:string;device:string;browser:string;source:string;durationMinutes:number};
type Data={visitors:Visitor[];summary:{total:number;anonymous:number;converted:number;online:number}};
const dateTime=new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"});
const duration=(minutes:number)=>minutes>=60?`${Math.floor(minutes/60)}h ${minutes%60}min`:`${minutes} min`;

export default function AdminVisitantes(){
  const {user,loading:authLoading}=useAuth({redirectOnUnauthenticated:true,redirectPath:"/login"}); const [,navigate]=useLocation();
  const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState<"all"|"anonymous"|"converted">("all");
  useEffect(()=>{if(!authLoading&&user&&!(user.role==="super_admin"||user.adminCanControlPanel))navigate("/dashboard",{replace:true});},[authLoading,navigate,user]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/site-access?scope=visitors",{credentials:"include",cache:"no-store"}),result=await response.json();if(!response.ok||!result.success)throw new Error(result.message||"Não foi possível carregar os visitantes.");setData(result);}catch(err){setError(err instanceof Error?err.message:"Não foi possível carregar os visitantes.");}finally{setLoading(false);}},[]);
  useEffect(()=>{if(user?.role==="super_admin"||user?.adminCanControlPanel)void load();},[load,user?.role,user?.adminCanControlPanel]);
  const visitors=useMemo(()=>{const term=query.trim().toLowerCase();return (data?.visitors||[]).filter(item=>(filter==="all"||(filter==="anonymous"&&item.anonymous)||(filter==="converted"&&item.converted))&&(!term||[item.label,item.email,item.city,item.region,item.country,item.maskedIp,item.source,item.browser,item.device,...(item.pages||[])].some(value=>String(value||"").toLowerCase().includes(term))));},[data?.visitors,filter,query]);
  if(authLoading||!user||!(user.role==="super_admin"||user.adminCanControlPanel))return null;
  const s=data?.summary;
  return <DashboardLayout><div className="space-y-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-sm font-bold text-primary"><Globe2 className="h-4 w-4"/>Super Admin</div><h1 className="mt-2 text-3xl font-black tracking-tight">Visitantes do site</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Acompanhe acessos anônimos dos últimos 30 dias. A localização é aproximada e o IP aparece protegido.</p></div><Button variant="outline" onClick={load} disabled={loading} className="rounded-xl">{loading?<LoaderCircle className="mr-2 h-4 w-4 animate-spin"/>:<RefreshCw className="mr-2 h-4 w-4"/>}Atualizar</Button></div>
    {error&&<div className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{error}</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Visitantes",s?.total||0,Users],["Anônimos",s?.anonymous||0,Globe2],["Cadastrados depois",s?.converted||0,UserCheck],["Ativos agora",s?.online||0,Eye]].map(([label,value,Icon]:any)=><Card key={label}><CardContent className="flex items-center justify-between p-5"><div><p className="text-sm font-semibold text-muted-foreground">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></div><div className="rounded-2xl bg-primary/10 p-3 text-primary"><Icon className="h-6 w-6"/></div></CardContent></Card>)}</div>
    <Card><CardContent className="p-4 sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="relative w-full max-w-lg"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar visitante, cidade, página ou origem" className="pl-9"/></div><div className="flex gap-2">{([['all','Todos'],['anonymous','Anônimos'],['converted','Cadastrados']] as const).map(([value,label])=><Button key={value} size="sm" variant={filter===value?"default":"outline"} onClick={()=>setFilter(value)}>{label}</Button>)}</div></div></CardContent></Card>
    <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-muted/50 text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3">Visitante</th><th className="px-4 py-3">Último acesso</th><th className="px-4 py-3">Local aproximado</th><th className="px-4 py-3">Aparelho</th><th className="px-4 py-3">Origem</th><th className="px-4 py-3">Navegação</th><th className="px-4 py-3">IP protegido</th></tr></thead><tbody className="divide-y">{visitors.map(item=><tr key={item.visitorId} className="align-top hover:bg-muted/20"><td className="px-4 py-4"><p className="font-bold">{item.label}</p><Badge variant={item.converted?"default":"secondary"} className="mt-2">{item.converted?"Cadastro identificado":"Anônimo"}</Badge>{item.email&&<p className="mt-1 text-xs text-muted-foreground">{item.email}</p>}</td><td className="whitespace-nowrap px-4 py-4"><p className="font-medium">{dateTime.format(new Date(item.lastSeen))}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="h-3.5 w-3.5"/>{duration(item.durationMinutes)}</p></td><td className="px-4 py-4"><p className="flex items-center gap-1.5 font-medium"><MapPin className="h-4 w-4 text-primary"/>{[item.city,item.region].filter(Boolean).join(" · ")||"Não disponível"}</p><p className="mt-1 text-xs text-muted-foreground">{item.country||"—"}</p></td><td className="px-4 py-4"><p className="flex items-center gap-1.5"><MonitorSmartphone className="h-4 w-4 text-primary"/>{item.device}</p><p className="mt-1 text-xs text-muted-foreground">{item.browser}{item.screen?` · ${item.screen}`:""}</p></td><td className="px-4 py-4 font-medium">{item.source}</td><td className="px-4 py-4"><p className="font-semibold">{item.pageViews} visualizações</p><p className="mt-1 max-w-[260px] truncate text-xs text-muted-foreground" title={(item.pages||[]).join(", ")}>{(item.pages||[]).join(", ")||"—"}</p></td><td className="px-4 py-4 font-mono text-xs">{item.maskedIp}</td></tr>)}{!loading&&!visitors.length&&<tr><td colSpan={7} className="px-4 py-12 text-center text-muted-foreground">Nenhum visitante encontrado.</td></tr>}{loading&&<tr><td colSpan={7} className="px-4 py-12 text-center text-muted-foreground"><LoaderCircle className="mx-auto mb-2 h-5 w-5 animate-spin"/>Carregando visitantes...</td></tr>}</tbody></table></div></Card>
    <p className="text-xs leading-5 text-muted-foreground">O nome só aparece quando o mesmo navegador realiza cadastro ou login. VPN, internet móvel e redes compartilhadas podem alterar IP e localização.</p>
  </div></DashboardLayout>;
}
