import { Button } from "@/components/ui/button";
import { CheckCheck, Clock3, Headphones, LoaderCircle, MessageCircle, Send, ShieldCheck } from "lucide-react";
import { FormEvent, KeyboardEvent, useCallback, useEffect, useRef, useState } from "react";
import { toast } from "sonner";

type Msg = { id:number; senderRole:"user"|"super_admin"; message:string; createdAt:string; senderName?:string };
const time = (value:string) => new Intl.DateTimeFormat("pt-BR", { hour:"2-digit", minute:"2-digit" }).format(new Date(value));
const day = (value:string) => { const date=new Date(value),today=new Date(),yesterday=new Date(); yesterday.setDate(today.getDate()-1); if(date.toDateString()===today.toDateString())return "Hoje"; if(date.toDateString()===yesterday.toDateString())return "Ontem"; return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"long"}).format(date); };

export default function SupportChat() {
  const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const [text,setText]=useState(""); const [supportId,setSupportId]=useState(""); const [messages,setMessages]=useState<Msg[]>([]);
  const endRef=useRef<HTMLDivElement>(null); const textareaRef=useRef<HTMLTextAreaElement>(null);
  const load=useCallback(async(silent=false)=>{try{const response=await fetch("/api/site-access?scope=support",{credentials:"include",cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data?.message||"Não foi possível abrir o suporte.");setSupportId(String(data.supportId||""));setMessages(Array.isArray(data.messages)?data.messages:[]);}catch(error){if(!silent)toast.error(error instanceof Error?error.message:"Erro ao abrir suporte.");}finally{if(!silent)setLoading(false);}},[]);
  useEffect(()=>{load();const timer=window.setInterval(()=>load(true),8000);return()=>window.clearInterval(timer);},[load]);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:loading?"auto":"smooth",block:"end"});},[messages.length,loading]);
  const send=async(event?:FormEvent)=>{event?.preventDefault();const message=text.trim();if(!message||sending)return;setSending(true);try{const response=await fetch("/api/site-access?scope=support",{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({message})});const data=await response.json();if(!response.ok)throw new Error(data?.message||"Não foi possível enviar a mensagem.");setText("");await load(true);textareaRef.current?.focus();}catch(error){toast.error(error instanceof Error?error.message:"Erro ao enviar mensagem.");}finally{setSending(false);}};
  const handleKeyDown=(event:KeyboardEvent<HTMLTextAreaElement>)=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();void send();}};
  let lastDay="";
  return <section id="suporte" className="overflow-hidden rounded-[1.75rem] border border-blue-100/80 bg-card shadow-[0_20px_70px_-38px_rgba(37,99,235,0.55)] dark:border-white/10">
    <div className="relative overflow-hidden border-b border-blue-100/70 bg-gradient-to-br from-blue-50 via-background to-cyan-50 p-5 dark:border-white/10 dark:from-blue-950/50 dark:via-card dark:to-cyan-950/30 sm:p-6"><div className="pointer-events-none absolute -right-12 -top-16 h-44 w-44 rounded-full bg-blue-400/10 blur-3xl"/><div className="relative flex flex-wrap items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-3.5"><div className="relative grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-cyan-500 text-white shadow-lg shadow-blue-500/20"><Headphones className="h-6 w-6"/><span className="absolute -bottom-0.5 -right-0.5 h-3.5 w-3.5 rounded-full border-[3px] border-white bg-emerald-500 dark:border-card"/></div><div className="min-w-0"><div className="flex items-center gap-2"><h2 className="text-lg font-extrabold tracking-tight sm:text-xl">Suporte Note Note</h2><span className="rounded-full bg-emerald-500/10 px-2 py-0.5 text-xs font-bold text-emerald-700 dark:text-emerald-300">Online</span></div><p className="mt-0.5 text-sm text-muted-foreground">Converse diretamente com nossa equipe.</p></div></div>{supportId?<div className="rounded-2xl border border-blue-100 bg-white/80 px-4 py-2.5 shadow-sm backdrop-blur dark:border-white/10 dark:bg-white/5"><p className="text-xs font-medium text-muted-foreground">ID do atendimento</p><p className="font-mono text-base font-extrabold tracking-[0.14em] text-foreground">{supportId}</p></div>:null}</div></div>
    <div className="bg-gradient-to-b from-muted/20 to-background p-3 sm:p-5"><div aria-live="polite" aria-busy={loading} className="support-scrollbar h-[min(25rem,55vh)] space-y-2 overflow-y-auto rounded-2xl border bg-background/80 p-3 shadow-inner sm:p-5">
      {loading?<div className="grid h-full place-items-center text-center"><div><LoaderCircle className="mx-auto h-7 w-7 animate-spin text-primary"/><p className="mt-3 text-sm font-medium text-muted-foreground">Abrindo seu atendimento...</p></div></div>:messages.length===0?<div className="grid h-full place-items-center px-5 text-center"><div className="max-w-xs"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-500/10 text-primary"><ShieldCheck className="h-7 w-7"/></div><p className="mt-4 text-lg font-bold">Como podemos ajudar?</p><p className="mt-1 text-sm leading-relaxed text-muted-foreground">Conte o que aconteceu. Nossa equipe responderá por aqui.</p></div></div>:messages.map(message=>{const currentDay=day(message.createdAt),showDay=currentDay!==lastDay;lastDay=currentDay;const mine=message.senderRole==="user";return <div key={message.id}>{showDay&&<div className="my-4 flex items-center gap-3"><span className="h-px flex-1 bg-border"/><span className="rounded-full border bg-muted/60 px-3 py-1 text-xs font-semibold text-muted-foreground">{currentDay}</span><span className="h-px flex-1 bg-border"/></div>}<div className={`group flex items-end gap-2 ${mine?"justify-end":"justify-start"}`}>{!mine&&<div className="mb-1 grid h-8 w-8 shrink-0 place-items-center rounded-full bg-gradient-to-br from-blue-600 to-cyan-500 text-white"><Headphones className="h-4 w-4"/></div>}<div className={`max-w-[84%] rounded-2xl px-4 py-3 text-[0.9375rem] shadow-sm ${mine?"rounded-br-md bg-gradient-to-br from-blue-600 to-blue-700 text-white shadow-blue-600/15":"rounded-bl-md border bg-card text-card-foreground"}`}><p className="whitespace-pre-wrap leading-relaxed">{message.message}</p><div className={`mt-1.5 flex items-center justify-end gap-1 text-[11px] ${mine?"text-blue-100":"text-muted-foreground"}`}><span>{time(message.createdAt)}</span>{mine&&<CheckCheck className="h-3.5 w-3.5"/>}</div></div></div></div>})}<div ref={endRef}/>
    </div><form onSubmit={send} className="mt-3 rounded-2xl border bg-background p-2 shadow-sm transition focus-within:border-primary/50 focus-within:shadow-[0_0_0_3px_rgba(59,130,246,0.1)]"><textarea ref={textareaRef} value={text} onChange={event=>setText(event.target.value)} onKeyDown={handleKeyDown} maxLength={5000} rows={2} aria-label="Mensagem para o suporte" placeholder="Escreva sua mensagem..." className="min-h-14 w-full resize-none bg-transparent px-2 py-2 text-base leading-relaxed outline-none placeholder:text-muted-foreground/70"/><div className="flex items-center justify-between gap-3 border-t px-1 pt-2"><p className="hidden items-center gap-1.5 text-xs text-muted-foreground sm:flex"><Clock3 className="h-3.5 w-3.5"/>Enter envia • Shift + Enter quebra a linha</p><span className="ml-auto text-xs text-muted-foreground">{text.length}/5000</span><Button type="submit" disabled={sending||!text.trim()} className="h-10 rounded-xl bg-gradient-to-r from-blue-600 to-blue-700 px-4 shadow-md shadow-blue-500/15 hover:from-blue-700 hover:to-blue-800"><span>{sending?"Enviando":"Enviar"}</span>{sending?<LoaderCircle className="h-4 w-4 animate-spin"/>:<Send className="h-4 w-4"/>}</Button></div></form><p className="mt-3 flex items-center justify-center gap-1.5 text-xs text-muted-foreground"><MessageCircle className="h-3.5 w-3.5"/>As respostas aparecem automaticamente nesta conversa.</p></div>
  </section>;
}
